### ISSUE TITLE
Gradle tasks 

### ISSUE THREAD

**Issue by aterreno** [boxfuse/boxfuse-issues#125]
Trying to run

```gradle build boxfuseRun -info``` 

gives back: 

* What went wrong:
Execution failed for task ':api:boxfuseRun'.
> Could not initialize class org.apache.http.conn.ssl.SSLConnectionSocketFactory

my build.gradle is pretty standard, with 

```classpath "com.boxfuse.client:boxfuse-gradle-plugin:1.23.0.1181"```

and 

```apply plugin: 'boxfuse'```

Stacktrace:

Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.apache.http.conn.ssl.SSLConnectionSocketFactory
        at org.apache.http.impl.client.HttpClientBuilder.build(HttpClientBuilder.java:962)
        at com.boxfuse.base.util.HttpUtils.createHttpClient(SourceFile:65)
        at com.boxfuse.client.core.a.b.b.a(SourceFile:360)
        at com.boxfuse.client.core.a.b.b.<init>(SourceFile:184)
        at com.boxfuse.client.core.Boxfuse.<init>(SourceFile:209)
        at com.boxfuse.client.core.Boxfuse.<init>(SourceFile:170)
        at com.boxfuse.client.gradle.task.AbstractBoxfuseTask.runTask(AbstractBoxfuseTask.java:533)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.doExecute(DefaultTaskClassInfoStore.java:136)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:129)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:118)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:623)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:606)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)

**Comment by aterreno** [comment]
So I solved it by configuring dependencies on my top level project, while if I configure/add dependencies on a child project it causes that error. 

Not digging further into this but I hope that sharing here might help people falling into the same issue.

**Comment by axelfontaine** [comment]
Thank you for investigating Antonio! Good to know. We'll keep a close eye on this to see if it affects more people.
