### ISSUE TITLE
Error while destroying instances during deploy

### ISSUE THREAD

**Issue by JoePipp** [boxfuse/boxfuse-issues#192]
We have intermittently seen a failure while destroying old instances after a deploy.
When this occurs, our new instances are up & active, and the old instances are taken down, just as during a successful build, but we receive a failing status code, which fails our automated build in Travis. 

Here is the failing section from our logs:
```
17:32:42.290 i-XXXXXXXXXXXXX9cb4 => 2017-11-20 17:32:37.592 ed.tomcat.TomcatEmbeddedServletContainer       main Tomcat started on port(s): 80 (http)

17:32:42.290 i-XXXXXXXXXXXXX9cb4 => 2017-11-20 17:32:37.601     com.companyname.ProductNameApplication       main Started ProductNameApplication in 10.204 seconds (JVM running for 10.392)

17:32:42.290 i-XXXXXXXXXXXXX9cb4 => 2017-11-20 17:32:37.653 ient.registration.ApplicationRegistrator ationTask1 Application registered itself as {id=b857c9e7, name=ProductName-prod, managementUrl=http://172.XX.XX.XX:8081/management, healthUrl=http://172.XX.XX.XX:8081/management/health, serviceUrl=http://172.XX.XX.XX:8081, statusInfo={status=UNKNOWN, timestamp=1511199157630, details={}}, source=http-api, metadata={}, info={}}

17:32:42.315 i-XXXXXXXXXXXXX9cb4 => 2017-11-20 17:32:37.759 ContainerBase.[Tomcat-1].[localhost].[/] 081-exec-1 Initializing Spring FrameworkServlet 'dispatcherServlet'

17:32:42.316 i-XXXXXXXXXXXXX9cb4 => 2017-11-20 17:32:37.759 gframework.web.servlet.DispatcherServlet 081-exec-1 FrameworkServlet 'dispatcherServlet': initialization started

17:32:42.316 i-XXXXXXXXXXXXX9cb4 => 2017-11-20 17:32:37.770 gframework.web.servlet.DispatcherServlet 081-exec-1 FrameworkServlet 'dispatcherServlet': initialization completed in 11 ms

17:32:42.316 ELB: i-XXXXXXXXXXXXX9cb4 [OutOfService] => Instance is in pending state.

17:32:52.885 ELB: i-XXXXXXXXXXXXX9cb4 [InService]

17:32:54.204 Destroying all Instances in Auto Scaling Group boxasg-companyname-productname-1.0.106 ...

17:33:12.844 Auto Scaling Group: i-XXXXXXXXXXXXX35d0 [Terminating]

17:34:17.803 Destroying Auto Scaling Group boxasg-companyname-productname-1.0.106 ...

17:34:41.630 Destroying Launch Configuration boxlc-companyname-productname-1.0.106 ...

17:34:41.630 Destroying all Instances in Auto Scaling Group boxasg-companyname-productname-1.0.103 ...

17:34:42.949 Destroying Security Group sg-be805fcb (boxsg-companyname-productname-1.0.106) ...

17:34:42.949 Destroying Security Group sg-10d51a65 (boxsg-companyname-productname-1.0.103) ...

17:34:46.921 ERROR: Running companyname/productname:1.0.107 failed!

com.boxfuse.base.exception.BoxfuseException: Running companyname/productname:1.0.107 failed!

	at com.boxfuse.client.core.Boxfuse.run(SourceFile:653)

	at com.boxfuse.client.commandline.Main.run(Main.java:325)

	at com.boxfuse.client.commandline.Main.main(Main.java:133)
```

**Comment by axelfontaine** [comment]
Thanks for the report. We'll investigate and get back to you.

**Comment by aweigold** [comment]
(I'm a co-worker of JoePipp), we are seeing this on multiple apps.  It appears that the deploys do succeed.  My first instinct was that perhaps a cleanup task in AWS was failing, but I can confirm that the blue Auto Scaling Group, Launch Configuration, and Security Groups are being removed via the EC2 console.  Perhaps there is a timeout or false response from AWS when the boxfuse client is querying it?

```
21:55:28.206 i-0836c847a62a58044 => 2017-11-29 21:55:25.597 gframework.web.servlet.DispatcherServlet 081-exec-2 FrameworkServlet 'dispatcherServlet': initialization completed in 12 ms
21:55:28.207 ELB: i-0836c847a62a58044 [InService]
21:55:28.207 Destroying all Instances in Auto Scaling Group boxasg-trustedchoicedev-sit-bighead-1.0.140 ...
21:55:53.702 Auto Scaling Group: i-02b1207c1b4b6a5a5 [Terminating]
21:57:14.981 Destroying Auto Scaling Group boxasg-trustedchoicedev-sit-bighead-1.0.140 ...
21:57:25.566 Destroying Launch Configuration boxlc-trustedchoicedev-sit-bighead-1.0.140 ...
21:57:25.566 Destroying Security Group sg-09a3327c (boxsg-trustedchoicedev-sit-bighead-1.0.140) ...
21:57:29.531 ERROR: Running trustedchoicedev/bighead:1.0.141 failed!
com.boxfuse.base.exception.BoxfuseException: Running trustedchoicedev/bighead:1.0.141 failed!
```
