### ISSUE TITLE
JHipster 5.5.0 cannot be deployed to aws with boxfuse. 

### ISSUE THREAD

**Issue by bonsmik** [boxfuse/boxfuse-issues#220]
I updated my application to JHipster 5.5.0 and now the deploy fails. I tried to generate a new application with 5.5.0 and its failing as well with the same problem:

`-01a513ac41c54ce4b => 2018-10-20 06:51:51.959 2018-10-20 06:51:51.951  INFO 1021 --- [           main] com.mycompany.myapp.TesmiApp             : Starting TesmiApp on i-01a513ac41c54ce4b with PID 1021 (/app/tesmi-0.0.1-SNAPSHOT.war started by root in /app)
i-01a513ac41c54ce4b => 2018-10-20 06:51:51.969 2018-10-20 06:51:51.968  INFO 1021 --- [           main] com.mycompany.myapp.TesmiApp             : The following profiles are active: prod
i-01a513ac41c54ce4b => 2018-10-20 06:52:04.492 2018-10-20 06:52:04.489 ERROR 1021 --- [           main] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Exception during pool initialization.
i-01a513ac41c54ce4b => 2018-10-20 06:52:04.492
i-01a513ac41c54ce4b => 2018-10-20 06:52:04.492 org.postgresql.util.PSQLException: Could not open SSL root certificate file //.postgresql/root.crt.
i-01a513ac41c54ce4b => 2018-10-20 06:52:04.492 	at org.postgresql.ssl.LibPQFactory.<init>(LibPQFactory.java:120)
i-01a513ac41c54ce4b => 2018-10-20 06:52:04.492 	at org.postgresql.core.SocketFactoryFactory.getSslSocketFactory(SocketFactoryFactory.java:61)
i-01a513ac41c54ce4b => 2018-10-20 06:52:04.492 	at org.postgresql.ssl.MakeSSL.convert(MakeSSL.java:33)
i-01a513ac41c54ce4b => 2018-10-20 06:52:04.492 	at org.postgresql.core.v3.ConnectionFactoryImpl.enableSSL(ConnectionFactoryImpl.java:435)
...`
The command I ran were:
jhipster 5.5.0 monolith app with postgresql
./gradlew -Pprod bootWar -x test
boxfuse run tesmi -env=test

**Comment by bonsmik** [comment]
Thanks for the reply. Can I somehow adjust the parameters for jdbc url? There is a environment variable for the url, but amazon rds url ain't static so not sure how to adjust the url.

**Comment by s-kin** [comment]
I set JDBC Driver version like this.
```xml
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <version>42.2.2</version>
        </dependency>
```

It works for me.
