### ISSUE TITLE
Boxfuse fails to download NewRelic JAR

### ISSUE THREAD

**Issue by lukaswelte** [boxfuse/boxfuse-issues#259]
Boxfuse client v.1.33.5.1506
Same issue with different NewRelic versions

Boxfuse conf:
```
# openjdk version
components.openjdk=8.131.11

# newrelic agent
components.newrelic-java=5.10.0
```

Error:
```
09:53:11.770 ERROR: Unable to download newrelic-java 5.10.0 from https://download.newrelic.com/newrelic/java-agent/newrelic-agent/5.10.0/newrelic-java-5.10.0.zip
com.boxfuse.base.exception.BoxfuseException: Unable to download newrelic-java 5.10.0 from https://download.newrelic.com/newrelic/java-agent/newrelic-agent/5.10.0/newrelic-java-5.10.0.zip
	at com.boxfuse.generator.inventory.Inventory.download(Inventory.java:169)
	at com.boxfuse.generator.inventory.Inventory.get(Inventory.java:117)
	at com.boxfuse.generator.builder.ramdisk.RamDiskBuilder.getComponent(RamDiskBuilder.java:117)
	at com.boxfuse.generator.builder.ramdisk.jvm.JvmRamDiskBuilder.doAdjustSpecBasedOnConfig(JvmRamDiskBuilder.java:102)
	at com.boxfuse.generator.builder.ramdisk.jvm.tomcat.TomcatRamDiskBuilder.doAdjustSpecBasedOnConfig(TomcatRamDiskBuilder.java:103)
	at com.boxfuse.generator.builder.ramdisk.RamDiskBuilder.adjustSpecBasedOnConfig(RamDiskBuilder.java:144)
	at com.boxfuse.generator.Generator.<init>(Generator.java:121)
	at com.boxfuse.client.core.Boxfuse.createGenerator(Boxfuse.java:393)
	at com.boxfuse.client.core.Boxfuse.fuse(Boxfuse.java:348)
	at com.boxfuse.client.core.Boxfuse.fuse(Boxfuse.java:327)
	at com.boxfuse.client.commandline.Main.fuse(Main.java:392)
	at com.boxfuse.client.commandline.Main.main(Main.java:112)
Caused by: com.boxfuse.base.exception.BoxfuseException: Download failed (unable to find valid certification path to requested target) => check your network connection and retry
	at com.boxfuse.base.util.HttpUtils.downloadWithProgress(HttpUtils.java:174)
	at com.boxfuse.generator.inventory.Inventory.download(Inventory.java:163)
	... 11 common frames omitted
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1509)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:914)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at com.boxfuse.base.util.HttpUtils.downloadWithProgress(HttpUtils.java:144)
	... 12 common frames omitted
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:387)
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292)
	at sun.security.validator.Validator.validate(Validator.java:260)
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1491)
	... 32 common frames omitted
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:382)
	... 38 common frames omitted
```

**Comment by axelfontaine** [comment]
Fixed in `1.33.6.1510`.
