### ISSUE TITLE
Play Framework 3.0 support

### ISSUE THREAD

**Issue by dpinn** [boxfuse/boxfuse-issues#295]
I've just upgraded from Play Framework 2.8.x to 3.0.1 and I find that the fuse command won't recognize the payload.

Here's the command that I'm executing:

```
boxfuse fuse risk-register-cloud-3.5.0.zip ^
-jvm.main.class=play.core.server.ProdServerStart ^
-components.newrelic-java=8.8.0 ^
-components.openjdk=17.0.7 ^
-healthcheck.path=/api/healthcheck
```

Here's the error message that appears in the console:

> ERROR: Unsupported payload: risk-register-cloud-3.5.0.zip => must be a Linux x64 (tar.gz), Go (ELF64 binary), Revel (tar.gz), Node.js (tgz), Spring Boot (jar or war), Grails (jar or war), Play (zip), Dropwizard (jar), Tomcat (war), TomEE (war) or executable jar application

Note that the payload includes an upgrade to Open JDK 17.
I'm on Windows 11 running the CloudCaptain Client v.1.35.5.1530.

Many thanks for your support.

**Comment by dpinn** [comment]
More information. I ran the fuse command using the -X option to obtain debug output. Here's the exception:

```
com.boxfuse.base.exception.BoxfuseException: Unsupported payload: risk-register-cloud-3.5.0.zip => must be a Linux x64 (tar.gz), Go (ELF64 binary), Revel (tar.gz), Node.js (tgz), Spring Boot (jar or war), Grails (jar or war), Play (zip), Dropwizard (jar), Tomcat (war), TomEE (war) or executable jar application
        at com.boxfuse.generator.payload.PayloadFactory.toPayload(PayloadFactory.java:314)
        at com.boxfuse.generator.image.ImageSpecImpl.resolvePayload(ImageSpecImpl.java:125)
        at com.boxfuse.generator.image.ImageSpecImpl.<init>(ImageSpecImpl.java:87)
        at com.boxfuse.generator.image.ImageSpecImpl.<init>(ImageSpecImpl.java:76)
        at com.boxfuse.client.core.Boxfuse.createImageSpec(Boxfuse.java:540)
        at com.boxfuse.client.core.Boxfuse.fuse(Boxfuse.java:325)
        at com.boxfuse.client.commandline.Main.fuse(Main.java:392)
        at com.boxfuse.client.commandline.Main.main(Main.java:112)
```

**Comment by axelfontaine** [comment]
You are not the only one:
- #294 

Let me see if we can repriotize this in case we can get it done with reasonable effort. I'll keep you updated.

**Comment by axelfontaine** [comment]
Version `1.36.0.2017` of the client is now out and supports Play 3.0 apps.

**Comment by dpinn** [comment]
Thank you, Axel. Much appreciated.
