### ISSUE TITLE
Unable to read Image

### ISSUE THREAD

**Issue by jtheuer** [boxfuse/boxfuse-issues#69]
When I run a boxfuse command I always get this message:

```
> boxfuse run -env=production
Boxfuse client v.1.18.7.938
Copyright 2016 Boxfuse GmbH. All rights reserved.

Account: ***

Unable to read Image: /Users/***/.boxfuse/work/Images/ba-1b40b4bfdc9244e394fb947b806d22a8.boxfuse
com.boxfuse.base.exception.BoxfuseException: Unable to read manifest from Image: /Users/***/.boxfuse/work/Images/ba-1b40b4bfdc9244e394fb947b806d22a8.boxfuse
	at com.boxfuse.generator.b.d.<init>(SourceFile:67)
	at com.boxfuse.generator.e.a.e(SourceFile:218)
	at com.boxfuse.generator.e.a.d(SourceFile:197)
	at com.boxfuse.generator.e.a.a(SourceFile:177)
	at com.boxfuse.client.core.Boxfuse.f(SourceFile:1248)
	at com.boxfuse.client.core.Boxfuse.run(SourceFile:479)
	at com.boxfuse.client.commandline.Main.run(Main.java:310)
	at com.boxfuse.client.commandline.Main.main(Main.java:93)
Caused by: java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:219)
	at java.util.zip.ZipFile.<init>(ZipFile.java:149)
	at java.util.zip.ZipFile.<init>(ZipFile.java:163)
	at com.boxfuse.base.util.ZipUtils.unzipSingleEntry(SourceFile:257)
	at com.boxfuse.generator.b.d.<init>(SourceFile:63)
	... 7 more
```
But it looks like boxfuse just continues without a problem.
Can I just delete the file? Not sure why it happened, maybe I killed a running boxfuse process?

Jan

**Comment by axelfontaine** [comment]
Yes, this indicates this image file somehow got corrupted. You can safely delete that file and the warning will go away.
